/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AgencyWalletsRouteImport } from './routes/agency.wallets'
import { Route as AgencyUsersRouteImport } from './routes/agency.users'
import { Route as AgencySupportRouteImport } from './routes/agency.support'
import { Route as AgencySettingsRouteImport } from './routes/agency.settings'
import { Route as AgencyInvoicesRouteImport } from './routes/agency.invoices'
import { Route as AgencyDashboardRouteImport } from './routes/agency.dashboard'
import { Route as AgencyAdAccountsRouteImport } from './routes/agency.ad-accounts'
import { Route as AgencyUsersUserIdRouteImport } from './routes/agency.users.$userId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyWalletsRoute = AgencyWalletsRouteImport.update({
  id: '/agency/wallets',
  path: '/agency/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyUsersRoute = AgencyUsersRouteImport.update({
  id: '/agency/users',
  path: '/agency/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencySupportRoute = AgencySupportRouteImport.update({
  id: '/agency/support',
  path: '/agency/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencySettingsRoute = AgencySettingsRouteImport.update({
  id: '/agency/settings',
  path: '/agency/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyInvoicesRoute = AgencyInvoicesRouteImport.update({
  id: '/agency/invoices',
  path: '/agency/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyDashboardRoute = AgencyDashboardRouteImport.update({
  id: '/agency/dashboard',
  path: '/agency/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyAdAccountsRoute = AgencyAdAccountsRouteImport.update({
  id: '/agency/ad-accounts',
  path: '/agency/ad-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyUsersUserIdRoute = AgencyUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AgencyUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/agency/ad-accounts': typeof AgencyAdAccountsRoute
  '/agency/dashboard': typeof AgencyDashboardRoute
  '/agency/invoices': typeof AgencyInvoicesRoute
  '/agency/settings': typeof AgencySettingsRoute
  '/agency/support': typeof AgencySupportRoute
  '/agency/users': typeof AgencyUsersRouteWithChildren
  '/agency/wallets': typeof AgencyWalletsRoute
  '/agency/users/$userId': typeof AgencyUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/agency/ad-accounts': typeof AgencyAdAccountsRoute
  '/agency/dashboard': typeof AgencyDashboardRoute
  '/agency/invoices': typeof AgencyInvoicesRoute
  '/agency/settings': typeof AgencySettingsRoute
  '/agency/support': typeof AgencySupportRoute
  '/agency/users': typeof AgencyUsersRouteWithChildren
  '/agency/wallets': typeof AgencyWalletsRoute
  '/agency/users/$userId': typeof AgencyUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/agency/ad-accounts': typeof AgencyAdAccountsRoute
  '/agency/dashboard': typeof AgencyDashboardRoute
  '/agency/invoices': typeof AgencyInvoicesRoute
  '/agency/settings': typeof AgencySettingsRoute
  '/agency/support': typeof AgencySupportRoute
  '/agency/users': typeof AgencyUsersRouteWithChildren
  '/agency/wallets': typeof AgencyWalletsRoute
  '/agency/users/$userId': typeof AgencyUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/set-password'
    | '/sign-up'
    | '/verify-email'
    | '/agency/ad-accounts'
    | '/agency/dashboard'
    | '/agency/invoices'
    | '/agency/settings'
    | '/agency/support'
    | '/agency/users'
    | '/agency/wallets'
    | '/agency/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/set-password'
    | '/sign-up'
    | '/verify-email'
    | '/agency/ad-accounts'
    | '/agency/dashboard'
    | '/agency/invoices'
    | '/agency/settings'
    | '/agency/support'
    | '/agency/users'
    | '/agency/wallets'
    | '/agency/users/$userId'
  id:
    | '__root__'
    | '/forgot-password'
    | '/login'
    | '/set-password'
    | '/sign-up'
    | '/verify-email'
    | '/agency/ad-accounts'
    | '/agency/dashboard'
    | '/agency/invoices'
    | '/agency/settings'
    | '/agency/support'
    | '/agency/users'
    | '/agency/wallets'
    | '/agency/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SignUpRoute: typeof SignUpRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AgencyAdAccountsRoute: typeof AgencyAdAccountsRoute
  AgencyDashboardRoute: typeof AgencyDashboardRoute
  AgencyInvoicesRoute: typeof AgencyInvoicesRoute
  AgencySettingsRoute: typeof AgencySettingsRoute
  AgencySupportRoute: typeof AgencySupportRoute
  AgencyUsersRoute: typeof AgencyUsersRouteWithChildren
  AgencyWalletsRoute: typeof AgencyWalletsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/wallets': {
      id: '/agency/wallets'
      path: '/agency/wallets'
      fullPath: '/agency/wallets'
      preLoaderRoute: typeof AgencyWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/users': {
      id: '/agency/users'
      path: '/agency/users'
      fullPath: '/agency/users'
      preLoaderRoute: typeof AgencyUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/support': {
      id: '/agency/support'
      path: '/agency/support'
      fullPath: '/agency/support'
      preLoaderRoute: typeof AgencySupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/settings': {
      id: '/agency/settings'
      path: '/agency/settings'
      fullPath: '/agency/settings'
      preLoaderRoute: typeof AgencySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/invoices': {
      id: '/agency/invoices'
      path: '/agency/invoices'
      fullPath: '/agency/invoices'
      preLoaderRoute: typeof AgencyInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/dashboard': {
      id: '/agency/dashboard'
      path: '/agency/dashboard'
      fullPath: '/agency/dashboard'
      preLoaderRoute: typeof AgencyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/ad-accounts': {
      id: '/agency/ad-accounts'
      path: '/agency/ad-accounts'
      fullPath: '/agency/ad-accounts'
      preLoaderRoute: typeof AgencyAdAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/users/$userId': {
      id: '/agency/users/$userId'
      path: '/$userId'
      fullPath: '/agency/users/$userId'
      preLoaderRoute: typeof AgencyUsersUserIdRouteImport
      parentRoute: typeof AgencyUsersRoute
    }
  }
}

interface AgencyUsersRouteChildren {
  AgencyUsersUserIdRoute: typeof AgencyUsersUserIdRoute
}

const AgencyUsersRouteChildren: AgencyUsersRouteChildren = {
  AgencyUsersUserIdRoute: AgencyUsersUserIdRoute,
}

const AgencyUsersRouteWithChildren = AgencyUsersRoute._addFileChildren(
  AgencyUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SetPasswordRoute: SetPasswordRoute,
  SignUpRoute: SignUpRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AgencyAdAccountsRoute: AgencyAdAccountsRoute,
  AgencyDashboardRoute: AgencyDashboardRoute,
  AgencyInvoicesRoute: AgencyInvoicesRoute,
  AgencySettingsRoute: AgencySettingsRoute,
  AgencySupportRoute: AgencySupportRoute,
  AgencyUsersRoute: AgencyUsersRouteWithChildren,
  AgencyWalletsRoute: AgencyWalletsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
